version: '3.3'

services:
  
  broker:
    image: rabbitmq:3.7.14-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
  
  nodered:
    image: faisalthaheem/open-lpr-nodered:main
    restart: always
    environment:
      - PORT=1890
      - BROKER_USERNAME=guest
      - BROKER_PASSWORD=guest
    ports:
      - '1890:1890'
    depends_on:
      - broker
      - mongodb
    volumes:
      - ./filestorage:/filestorage
      - ./static-html-content:/static-html-content
  
  mongodb:
    image: mongo:4.1.11-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lpr
      MONGO_INITDB_ROOT_PASSWORD: lpr
      MONGO_INITDB_DATABASE: openlpr
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
  
  redis:
    image: redis:6
    restart: always
    ports:
      - 6379:6379