version: '3.3'
services:
  
  nodered:
    volumes:
      - shared:/filestorage
  
  ftp:
    image: faisalthaheem/open-lpr-ftp:main
    restart: always
    environment:
      PRODUCTION: production
    depends_on:
      - broker
      - mongodb
    ports:
      - 2121:2121
      - 60000-60050:60000-60050
    volumes:
      - shared:/filestorage
  
  platedetector:
    image: faisalthaheem/open-lpr-plate-detection:main
    restart: always
    environment:
      PRODUCTION: production
    depends_on:
      - broker
      - mongodb
    volumes:
      - shared:/filestorage
  
  ocr:
      image: faisalthaheem/open-lpr-ocr:main
      restart: always
      environment:
        PRODUCTION: production
      depends_on:
        - broker
        - mongodb
      volumes:
        - shared:/filestorage
  
  rest:
      image: faisalthaheem/open-lpr-rest:main
      restart: always
      environment:
        PRODUCTION: production
      depends_on:
        - broker
        - mongodb
      ports:
        - 5000:5000
      volumes:
        - shared:/filestorage

volumes:
  shared:
    driver: local
    driver_opts:
      type: none
      device: $PWD/filestorage
      o: bind