version: '3.3'
services:
  nodered:
    volumes:
      - shared:/filestorage
  ftp:
    image: openlpr/ftp:3.0
    restart: always
    environment:
      PRODUCTION: production
    depends_on:
      - broker
      - mongodb
    ports:
      - 2121:2121
      - 60000-60050:60000-60050
    volumes:
      - shared:/filestorage
  platedetector:
    image: openlpr/platedetector:3.0
    restart: always
    environment:
      PRODUCTION: production
    depends_on:
      - broker
      - mongodb
    volumes:
      - shared:/filestorage
  ocr:
      image: openlpr/ocr:3.0
      restart: always
      environment:
        PRODUCTION: production
      depends_on:
        - broker
        - mongodb
      volumes:
        - shared:/filestorage
  rest:
      image: openlpr/rest:3.0
      restart: always
      environment:
        PRODUCTION: production
      depends_on:
        - broker
        - mongodb
      ports:
        - 5000:5000
      volumes:
        - shared:/filestorage
volumes:
  shared:
    driver: local
    driver_opts:
      type: none
      device: $PWD/../filestorage
      o: bind